apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: thrush-nodejs 
  janus-idp.io/tekton: thrush-nodejs
  backstage.io/kubernetes-id: thrush-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: thrush-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  